#!/bin/sh
set -eu

pubspec_file="pubspec.yaml"
app_version_file="lib/src/app_version.dart"

if [ ! -f "$pubspec_file" ]; then
  echo "pre-commit: pubspec.yaml not found" >&2
  exit 1
fi

version_line=$(grep -E '^version:[[:space:]]*[0-9]+[.][0-9]+[.][0-9]+[+][0-9]+[[:space:]]*$' "$pubspec_file" || true)
if [ -z "$version_line" ]; then
  echo "pre-commit: expected version format like 'version: 1.0.0+1' in pubspec.yaml" >&2
  exit 1
fi

version_value=$(printf '%s\n' "$version_line" | sed -E 's/^version:[[:space:]]*//')
version_name=${version_value%+*}
build_number=${version_value#*+}
next_build_number=$((build_number + 1))
next_version_value="${version_name}+${next_build_number}"
next_version="version: ${next_version_value}"

tmp_file=$(mktemp)
sed -E "s/^version:[[:space:]]*[0-9]+[.][0-9]+[.][0-9]+[+][0-9]+[[:space:]]*$/$(printf '%s' "$next_version" | sed 's/[\/&]/\\&/g')/" "$pubspec_file" > "$tmp_file"
mv "$tmp_file" "$pubspec_file"

if [ -f "$app_version_file" ]; then
  tmp_file=$(mktemp)
  sed -E "s/^const String appVersion = '.*';$/const String appVersion = '${next_version_value}';/" "$app_version_file" > "$tmp_file"
  mv "$tmp_file" "$app_version_file"
fi

git add "$pubspec_file" "$app_version_file"
echo "pre-commit: bumped app build number to ${next_version_value}"
